import AppLayout from "@/components/AppLayout"
import Button from "@/components/Button"
import Head from "next/head"

export default function Home() {
    return (
        <>
            <Head>
                <title>Beranda | Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout>
                <div className="container py-10">
                    <Button className="text-white" type="button">
                        Login
                    </Button>
                </div>
            </AppLayout>
        </>
    )
}
